package entities;
// Generated Feb 20, 2018 8:06:48 AM by Hibernate Tools 4.3.1



/**
 * Actor generated by hbm2java
 */
public class Actor  implements java.io.Serializable {


     private Integer idActor;
     private String name;
     private Integer idMovie;

    public Actor() {
    }

    public Actor(String name, Integer idMovie) {
       this.name = name;
       this.idMovie = idMovie;
    }
   
    public Integer getIdActor() {
        return this.idActor;
    }
    
    public void setIdActor(Integer idActor) {
        this.idActor = idActor;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getIdMovie() {
        return this.idMovie;
    }
    
    public void setIdMovie(Integer idMovie) {
        this.idMovie = idMovie;
    }




}


