package entities;
// Generated Feb 20, 2018 8:06:48 AM by Hibernate Tools 4.3.1



/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private int idRes;
     private Integer rate;
     private String comment;
     private Integer idMovie;

    public Feedback() {
    }

	
    public Feedback(int idRes) {
        this.idRes = idRes;
    }
    public Feedback(int idRes, Integer rate, String comment, Integer idMovie) {
       this.idRes = idRes;
       this.rate = rate;
       this.comment = comment;
       this.idMovie = idMovie;
    }
   
    public int getIdRes() {
        return this.idRes;
    }
    
    public void setIdRes(int idRes) {
        this.idRes = idRes;
    }
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Integer getIdMovie() {
        return this.idMovie;
    }
    
    public void setIdMovie(Integer idMovie) {
        this.idMovie = idMovie;
    }




}


