package entities;
// Generated Feb 20, 2018 8:06:48 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private Integer idFest;
     private Date dateFrom;
     private Date dateTo;
     private String name;
     private String info;
     private Integer ticketNum;

    public Festival() {
    }

    public Festival(Date dateFrom, Date dateTo, String name, String info, Integer ticketNum) {
       this.dateFrom = dateFrom;
       this.dateTo = dateTo;
       this.name = name;
       this.info = info;
       this.ticketNum = ticketNum;
    }
   
    public Integer getIdFest() {
        return this.idFest;
    }
    
    public void setIdFest(Integer idFest) {
        this.idFest = idFest;
    }
    public Date getDateFrom() {
        return this.dateFrom;
    }
    
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }
    public Date getDateTo() {
        return this.dateTo;
    }
    
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Integer getTicketNum() {
        return this.ticketNum;
    }
    
    public void setTicketNum(Integer ticketNum) {
        this.ticketNum = ticketNum;
    }




}


