package entities;
// Generated Feb 14, 2018 12:46:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private Integer idFest;
     private Date dateFrom;
     private Date dateTo;
     private String name;

    public Festival() {
    }

    public Festival(Date dateFrom, Date dateTo, String name) {
       this.dateFrom = dateFrom;
       this.dateTo = dateTo;
       this.name = name;
    }
   
    public Integer getIdFest() {
        return this.idFest;
    }
    
    public void setIdFest(Integer idFest) {
        this.idFest = idFest;
    }
    public Date getDateFrom() {
        return this.dateFrom;
    }
    
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }
    public Date getDateTo() {
        return this.dateTo;
    }
    
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


