package entities;
// Generated Feb 20, 2018 8:32:24 PM by Hibernate Tools 4.3.1



/**
 * Galery generated by hbm2java
 */
public class Galery  implements java.io.Serializable {


     private Integer idG;
     private String picture;
     private Integer idMovie;

    public Galery() {
    }

    public Galery(String picture, Integer idMovie) {
       this.picture = picture;
       this.idMovie = idMovie;
    }
   
    public Integer getIdG() {
        return this.idG;
    }
    
    public void setIdG(Integer idG) {
        this.idG = idG;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public Integer getIdMovie() {
        return this.idMovie;
    }
    
    public void setIdMovie(Integer idMovie) {
        this.idMovie = idMovie;
    }




}


