package entities;
// Generated Feb 20, 2018 8:32:24 PM by Hibernate Tools 4.3.1



/**
 * Hall generated by hbm2java
 */
public class Hall  implements java.io.Serializable {


     private Integer idHall;
     private Integer idLok;

    public Hall() {
    }

    public Hall(Integer idLok) {
       this.idLok = idLok;
    }
   
    public Integer getIdHall() {
        return this.idHall;
    }
    
    public void setIdHall(Integer idHall) {
        this.idHall = idHall;
    }
    public Integer getIdLok() {
        return this.idLok;
    }
    
    public void setIdLok(Integer idLok) {
        this.idLok = idLok;
    }




}


