package entities;
// Generated Feb 20, 2018 8:32:24 PM by Hibernate Tools 4.3.1



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer idLok;
     private String building;
     private String adress;

    public Location() {
    }

    public Location(String building, String adress) {
       this.building = building;
       this.adress = adress;
    }
   
    public Integer getIdLok() {
        return this.idLok;
    }
    
    public void setIdLok(Integer idLok) {
        this.idLok = idLok;
    }
    public String getBuilding() {
        return this.building;
    }
    
    public void setBuilding(String building) {
        this.building = building;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }




}


