package entities;
// Generated Feb 18, 2018 8:22:58 PM by Hibernate Tools 4.3.1



/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private Integer idMovie;
     private String name;
     private String picture;
     private Integer year;
     private String about;
     private String director;
     private Integer length;
     private String country;
     private String imdb;
     private String tomato;
     private String youtube;

    public Movie() {
    }

    public Movie(String name, String picture, Integer year, String about, String director, Integer length, String country, String imdb, String tomato, String youtube) {
       this.name = name;
       this.picture = picture;
       this.year = year;
       this.about = about;
       this.director = director;
       this.length = length;
       this.country = country;
       this.imdb = imdb;
       this.tomato = tomato;
       this.youtube = youtube;
    }
   
    public Integer getIdMovie() {
        return this.idMovie;
    }
    
    public void setIdMovie(Integer idMovie) {
        this.idMovie = idMovie;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public Integer getLength() {
        return this.length;
    }
    
    public void setLength(Integer length) {
        this.length = length;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getImdb() {
        return this.imdb;
    }
    
    public void setImdb(String imdb) {
        this.imdb = imdb;
    }
    public String getTomato() {
        return this.tomato;
    }
    
    public void setTomato(String tomato) {
        this.tomato = tomato;
    }
    public String getYoutube() {
        return this.youtube;
    }
    
    public void setYoutube(String youtube) {
        this.youtube = youtube;
    }




}


