package entities;
// Generated Feb 20, 2018 8:32:24 PM by Hibernate Tools 4.3.1



/**
 * OnFestId generated by hbm2java
 */
public class OnFestId  implements java.io.Serializable {


     private int idFest;
     private int idProjection;

    public OnFestId() {
    }

    public OnFestId(int idFest, int idProjection) {
       this.idFest = idFest;
       this.idProjection = idProjection;
    }
   
    public int getIdFest() {
        return this.idFest;
    }
    
    public void setIdFest(int idFest) {
        this.idFest = idFest;
    }
    public int getIdProjection() {
        return this.idProjection;
    }
    
    public void setIdProjection(int idProjection) {
        this.idProjection = idProjection;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OnFestId) ) return false;
		 OnFestId castOther = ( OnFestId ) other; 
         
		 return (this.getIdFest()==castOther.getIdFest())
 && (this.getIdProjection()==castOther.getIdProjection());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFest();
         result = 37 * result + this.getIdProjection();
         return result;
   }   


}


