package entities;
// Generated Feb 18, 2018 8:22:58 PM by Hibernate Tools 4.3.1



/**
 * OnFest generated by hbm2java
 */
public class OnFest  implements java.io.Serializable {


     private OnFestId id;

    public OnFest() {
    }

    public OnFest(OnFestId id) {
       this.id = id;
    }
   
    public OnFestId getId() {
        return this.id;
    }
    
    public void setId(OnFestId id) {
        this.id = id;
    }




}


