package entities;
// Generated Feb 20, 2018 8:32:24 PM by Hibernate Tools 4.3.1



/**
 * OnLocationId generated by hbm2java
 */
public class OnLocationId  implements java.io.Serializable {


     private int idFest;
     private int idLok;

    public OnLocationId() {
    }

    public OnLocationId(int idFest, int idLok) {
       this.idFest = idFest;
       this.idLok = idLok;
    }
   
    public int getIdFest() {
        return this.idFest;
    }
    
    public void setIdFest(int idFest) {
        this.idFest = idFest;
    }
    public int getIdLok() {
        return this.idLok;
    }
    
    public void setIdLok(int idLok) {
        this.idLok = idLok;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OnLocationId) ) return false;
		 OnLocationId castOther = ( OnLocationId ) other; 
         
		 return (this.getIdFest()==castOther.getIdFest())
 && (this.getIdLok()==castOther.getIdLok());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFest();
         result = 37 * result + this.getIdLok();
         return result;
   }   


}


