package entities;
// Generated Feb 18, 2018 8:22:58 PM by Hibernate Tools 4.3.1



/**
 * OnLocation generated by hbm2java
 */
public class OnLocation  implements java.io.Serializable {


     private OnLocationId id;

    public OnLocation() {
    }

    public OnLocation(OnLocationId id) {
       this.id = id;
    }
   
    public OnLocationId getId() {
        return this.id;
    }
    
    public void setId(OnLocationId id) {
        this.id = id;
    }




}


