package entities;
// Generated Feb 18, 2018 8:22:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Projection generated by hbm2java
 */
public class Projection  implements java.io.Serializable {


     private Integer idProjection;
     private Integer version;
     private Integer idMovie;
     private Integer idHall;
     private Date date;
     private String status;
     private Integer price;

    public Projection() {
    }

    public Projection(Integer idMovie, Integer idHall, Date date, String status, Integer price) {
       this.idMovie = idMovie;
       this.idHall = idHall;
       this.date = date;
       this.status = status;
       this.price = price;
    }
   
    public Integer getIdProjection() {
        return this.idProjection;
    }
    
    public void setIdProjection(Integer idProjection) {
        this.idProjection = idProjection;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public Integer getIdMovie() {
        return this.idMovie;
    }
    
    public void setIdMovie(Integer idMovie) {
        this.idMovie = idMovie;
    }
    public Integer getIdHall() {
        return this.idHall;
    }
    
    public void setIdHall(Integer idHall) {
        this.idHall = idHall;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }




}


